version: "3.7"

services:
  kapten:
    image: 5monkeys/kapten:${KAPTEN_IMAGE_TAG:-latest}
    build:
      context: .
      args:
        BUILD_TARGET: dev
    ports:
      - 8000:8000
    volumes:
      - ./kapten:/app/kapten
      - ./tests:/app/tests
      - ./setup.cfg:/app/setup.cfg
      - ./Makefile:/app/Makefile
